version: 2.1
orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:
  test:
    docker:
      - image: cimg/node:13.12-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command:  chromedriver --version
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: chromeDriver
          command: npm i wdio-chromedriver-service
      - run:
          name: Run Tests
          command: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test









# version: 2.1

# jobs:
#   build-and-test:
#     docker:
#       - image: node:latest
#     steps:
#       - checkout
#       - run:
#           name: Install Node.js 18
#           command: |
#             curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#             source ~/.nvm/nvm.sh
#             nvm install 18
#             node --version
#       - run:
#           name: Install Dependencies
#           command: npm ci
#       - run:
#           name: chromeDriver
#           command: npm i wdio-chromedriver-service
#       - run:
#           name: Run Tests
#           command: npm run test

# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - build-and-test



