version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

