version: 2.1

executors:
  node-executor:
    shell:
      - /bin/bash
      - --login

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node.js 18
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 18
            node --version
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test


