version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test



