version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: node --unhandled-rejections=strict node_modules/.bin/wdio

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

